import type {REVIEWS_BY_CLIENT_QUERY_RESULT} from '../../sanity.types'
import {slugify} from './slug'

/**
 * Turning a flat list of clients into the Reviews page's three-level structure.
 *
 * The query does what GROQ can do — selecting clients that have reviews and ordering
 * them by their most recent engagement. What is left is the two rules GROQ cannot
 * express: grouping by a relationship whose ORDER is editorial rather than alphabetical,
 * and sorting reviews by a last name that is not a field.
 */

type Client = REVIEWS_BY_CLIENT_QUERY_RESULT[number]
type Review = Client['reviews'][number]

/** The four values `client.relationship` can hold, straight from the generated types. */
export type Relationship = NonNullable<Client['relationship']>

/**
 * ── GROUP ORDER IS EDITORIAL, SO IT IS WRITTEN DOWN ─────────────────────────
 *
 * Direct clients first, then agency partners, coworkers and students — the board's
 * order, and the rail's. No property of the data produces it: alphabetically it would be
 * Agency Partner first, and by recency Students would land third.
 *
 * ── A `Record`, NOT AN ARRAY, AND THE EXHAUSTIVENESS IS THE REASON ──────────
 *
 * `Record<Relationship, number>` cannot be written with a key missing. `relationship` is
 * generated by TypeGen as a literal union off the Studio's option list, so ADDING A
 * FIFTH RELATIONSHIP IN THE STUDIO BREAKS THIS BUILD — with a type error naming the
 * value, at the one place that has to decide where it sorts.
 *
 * An ordered array would have been the obvious shape and gets this wrong quietly: a new
 * value simply would not appear in it, and `indexOf` returning -1 would sort the new
 * group silently to the top. The failure mode is the whole argument.
 */
const RELATIONSHIP_ORDER: Record<Relationship, number> = {
  'Direct Client': 0,
  'Agency Partner': 1,
  Coworker: 2,
  Student: 3,
}

/**
 * ── THE HEADING IS THE STORED VALUE PLUS AN "s" ─────────────────────────────
 *
 * Andy's rule (2026-09-03), and it deliberately overrides two other candidates. The
 * Studio's display TITLES say "Former Employer" and "Teaching Institution", which
 * describe the client and would read as headings over a list of reviewers. The board
 * draws "Direct clients" and "Agency Partners", which disagree with each other on case.
 *
 * So the value is the label: "Direct Clients", "Agency Partners", "Coworkers",
 * "Students". Deriving rather than mapping means a fifth relationship gets a correct
 * heading for free, and there is no second vocabulary to keep in step with the schema.
 *
 * Naive pluralisation is safe on a closed four-value list where none ends in s, x, z, ch
 * or y. If that stops being true this needs a real rule, not a special case.
 */
function label(relationship: Relationship): string {
  return `${relationship}s`
}

/**
 * ── SORTING BY A LAST NAME THAT IS NOT A FIELD ──────────────────────────────
 *
 * `author` is one string — "Lisa Crounse", "Turi Henderson-Palmer", "Arup Roy-Burman
 * MD" — so the last name has to be derived, and deriving a surname from a full name is
 * unsolvable in general. What makes it tractable is the scope: it only orders reviews
 * WITHIN one client, so it runs on five sets of two and one set of three. Sixteen of the
 * 22 reviews are the only review their client has and never reach a comparison.
 *
 * Last whitespace-separated token, after dropping a suffix. The suffix list exists for
 * "Arup Roy-Burman MD", the one name in the data with one: without it the sort key is
 * "md" rather than "roy-burman".
 *
 * NOTE THAT THE ONE CASE IT MATTERS FOR WOULD SORT CORRECTLY ANYWAY — "crounse" sorts
 * before both "md" and "roy-burman", so Elemeno's two reviews come out in the same order
 * either way. The list is here because that is a coincidence of this data, not a
 * property of the rule, and a coincidence is not a thing to depend on.
 *
 * `localeCompare` rather than `<`: it puts "DeMenthon" where a reader expects it and
 * handles the hyphenated and accented names this list already contains.
 */
const NAME_SUFFIXES = new Set([
  'jr',
  'sr',
  'ii',
  'iii',
  'iv',
  'md',
  'phd',
  'dphil',
  'mba',
  'ma',
  'ms',
  'msc',
  'esq',
])

function sortKey(author: string | null): string {
  if (!author) return ''
  const parts = author
    .trim()
    .split(/\s+/)
    .filter((part) => !NAME_SUFFIXES.has(part.replace(/\./g, '').toLowerCase()))
  return parts.at(-1) ?? author
}

export interface RelationshipGroup {
  relationship: Relationship
  /** The h2, and the rail link's text. */
  label: string
  /** The h2's fragment id, which the rail links to. */
  id: string
  clients: Array<Client & {reviews: Review[]}>
}

/**
 * Group clients by relationship, ordered by RELATIONSHIP_ORDER, reviews sorted by the
 * author's last name.
 *
 * ── CLIENT ORDER IS INHERITED, NOT RECOMPUTED ───────────────────────────────
 *
 * The query returns all 16 clients sorted by their latest engagement end date, and this
 * function never re-sorts them: it appends to each group in the order it receives them,
 * and a stable partition of a sorted list leaves every part sorted. So "most recent
 * first" is stated once, in GROQ, and there is no second ordering rule here that could
 * come to disagree with it.
 *
 * ── EMPTY GROUPS CANNOT HAPPEN ─────────────────────────────────────────────
 *
 * Groups are built from the clients present rather than from RELATIONSHIP_ORDER's keys,
 * so a relationship with no reviewed clients produces no heading and no rail entry.
 * Today all four are populated. The page therefore needs no empty-state branch, and the
 * rail is built from the same array it will link to — the two cannot disagree about
 * which sections exist.
 *
 * A client with no relationship is dropped. The field is `validation: required()`, so
 * this is unreachable through the Studio; it is here because the generated type admits
 * null and silently placing such a client in an arbitrary group would be worse.
 */
export function groupByRelationship(clients: Client[]): RelationshipGroup[] {
  const groups = new Map<Relationship, Client[]>()

  for (const client of clients) {
    if (!client.relationship) continue
    const bucket = groups.get(client.relationship)
    if (bucket) bucket.push(client)
    else groups.set(client.relationship, [client])
  }

  return [...groups]
    .sort(([a], [b]) => RELATIONSHIP_ORDER[a] - RELATIONSHIP_ORDER[b])
    .map(([relationship, grouped]) => ({
      relationship,
      label: label(relationship),
      id: slugify(label(relationship)),
      clients: grouped.map((client) => ({
        ...client,
        reviews: [...client.reviews].sort((a, b) =>
          sortKey(a.author).localeCompare(sortKey(b.author)),
        ),
      })),
    }))
}
