name: Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy 11ty development site
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Branch
          uses: actions/checkout@v4

        - name: Make envfile
          uses: SpicyPizza/create-envfile@v2.0
          with:
            envkey_RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
            envkey_AFC_MAIL_USERNAME: ${{ secrets.AFC_MAIL_USERNAME }}
            envkey_AFC_MAIL_PASSWORD: ${{ secrets.AFC_MAIL_PASSWORD }}
            envkey_ELEVENTY_ENVIRONMENT: development
            directory: web
        
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install Project Dependencies
          run: npm ci --legacy-peer-deps
          working-directory: web

        - name: Build 11ty
          run: npx @11ty/eleventy
          working-directory: web
        
        - name: Verify build
          run: ls -la _site
          working-directory: web

        - name: Copy .env into build output
          run: cp web/.env web/_site/.env

        - name: Set Up SSH
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.AFC_SSH_KEY }}" > ~/.ssh/afc
            sudo chmod 600 ~/.ssh/afc
            ssh-keyscan -H "24.199.98.130" > ~/.ssh/known_hosts

        - name: Clean & SFTP Upload
          run: |
            ssh -i ~/.ssh/afc afc@24.199.98.130 "rm -rf /var/www/dev.andyfitzgeraldconsulting.com/html/*"
            sftp -i ~/.ssh/afc afc@24.199.98.130 <<'SFTP'
              cd /var/www/dev.andyfitzgeraldconsulting.com/html
              lcd web/_site
              put -r .
              SFTP

        - name: Fix .env permissions
          run: |
            ssh -i ~/.ssh/afc afc@24.199.98.130 \
            "sudo chgrp www-data /var/www/dev.andyfitzgeraldconsulting.com/html/.env || true; \
             sudo chmod 640 /var/www/dev.andyfitzgeraldconsulting.com/html/.env || true"

        - name: Install Composer & PHP deps on Server
          run: |
            ssh -i ~/.ssh/afc afc@24.199.98.130 <<'EOF'
            set -e
            cd /var/www/dev.andyfitzgeraldconsulting.com/html
            # Install Composer if missing
            if ! command -v composer >/dev/null 2>&1; then
              php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
              php composer-setup.php --install-dir=$HOME/.local/bin --filename=composer
              rm -f composer-setup.php
              export PATH="$HOME/.local/bin:$PATH"
            fi
            # Ensure PATH includes composer location for this session
            if [ -f "$HOME/.local/bin/composer" ]; then
              export PATH="$HOME/.local/bin:$PATH"
            fi
            # Install/Update PHP dependencies (recreates vendor/ after clean)
            composer require --prefer-dist phpmailer/phpmailer vlucas/phpdotenv
            EOF