name: Studio

on:
  push:
    paths: 
      - 'studio/**'
  workflow_dispatch: 

jobs:
  build-and-deploy:
    name: Build & Deploy Sanity Studio
    if: ${{ github.ref == 'refs/heads/main' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Project Dependencies
        run: npm ci --legacy-peer-deps
        working-directory: studio

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli
        working-directory: studio

      - name: Build Studio
        run: sanity build
        working-directory: studio

      - name: Verify Build
        run: ls -la dist
        working-directory: studio

      - name: Extract Studio Manifest
        run: sanity manifest extract --output studio/dist/static
        working-directory: studio

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.AFC_SSH_KEY }}" > ~/.ssh/afc
          sudo chmod 600 ~/.ssh/afc
          ssh-keyscan -H "24.199.98.130" > ~/.ssh/known_hosts

      - name: SFTP Upload
        run: sftp -i ~/.ssh/afc afc@24.199.98.130 <<< $'cd /var/www/cms.andyfitzgeraldconsulting.com/html \n put -r studio/dist/*'