name: Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy 11ty site
    runs-on: ubuntu-latest
    # env:
    #   ELEVENTY_STAGING: true
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2.3.1

        - name: Make envfile
          uses: SpicyPizza/create-envfile@v1.3
          with:
            envkey_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET }}
            envkey_ELEVENTY_ENVIRONMENT: staging
        
        - name: Install Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '18.x'

        - name: Install Project Dependencies
          run: npm ci --legacy-peer-deps
          working-directory: web

        - name: Build 11ty
          run: ELEVENTY_ENVIRONMENT=staging npx @11ty/eleventy
          working-directory: web

        - name: Compile SCSS
          run: npx sass style:_site/style
          working-directory: web
        
        - name: Verify build
          run: ls -la _site
          working-directory: web

        # - name: Set Up SSH
        #   run: |
        #     mkdir -p ~/.ssh/
        #     echo "${{ secrets.UXM_DEV_DREAMHOST_SSH_KEY }}" > ~/.ssh/uxm_dev
        #     sudo chmod 600 ~/.ssh/uxm_dev
        #     ssh-keyscan -H "jacksonville.dreamhost.com" > ~/.ssh/known_hosts

        # - name: SFTP Upload
        #   run: sftp -i ~/.ssh/uxm_dev uxm_dev@jacksonville.dreamhost.com <<< $'cd dev.uxmethods.org \n put -r web/public/*'